version: '3'
services:
  app:
    build: .
    command: sleep infinity
    volumes:
      - ..:/app
    links:
      - redis
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis:4-alpine
    ports:
      - '9379:6379'
