import Head from 'next/head'
import { Top, TopCell, Categories } from '../styles/home';
import CategoryCard from '../components/CategoryCard';
import { useCateogries } from '../hooks/categories';

export default function App() {
  const [loadingCategories, categories] = useCateogries()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Top>
          <TopCell>aaaa</TopCell>
          <TopCell>bbbb</TopCell>
          <TopCell>cccc</TopCell>
        </Top>
        <Categories>
          {loadingCategories ?
            <span>Loaidng...</span> :
            categories.map((item, i) => <CategoryCard key={i} item={item} i={i} />)
          }
        </Categories>
      </main>
    </>
  )
}
