import Head from 'next/head'
import {Top, TopCell} from '../styles/home';

export default function App() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Top>
          <TopCell>aaaa</TopCell>
          <TopCell>bbbb</TopCell>
          <TopCell>cccc</TopCell>
        </Top>
      </main>
    </>
  )
}
